ALTER TABLE agents
  ADD COLUMN bank_name VARCHAR(255) DEFAULT NULL,
  ADD COLUMN branch_name VARCHAR(255) DEFAULT NULL,
  ADD COLUMN account_holder VARCHAR(255) DEFAULT NULL,
  ADD COLUMN account_number VARCHAR(100) DEFAULT NULL,
  ADD COLUMN iban VARCHAR(100) DEFAULT NULL,
  ADD COLUMN swift_code VARCHAR(50) DEFAULT NULL,
  ADD COLUMN payment_instructions TEXT DEFAULT NULL,
  ADD COLUMN paypal_email VARCHAR(255) DEFAULT NULL;
